---
title: "Welcome to EPSY 630!"
author: "Jason Bryer"
date: 2021-01-15
draft: false
categories: ["R"]
tags: ["Annoucement"]
---

Welcome to EPSY 630! My name is Dr. Jason Bryer and I will be your instructor for this semester. I am an Assistant Professor at the School of Professional Studies at CUNY and a graduate of the Educational Psychology and Methodology program. Couple of important notes as you get started:

* The course syllabus located here: https://epsy630.bryer.org/course-overview I will post all course materials there. Blackboard will be used primarily for submitting assignments. **Please read the syllabus carefully!** Send me any questions you may still have about the course.
* Complete this [Google Form](https://forms.gle/fPL2oWCAYwRWwp1R9) as soon as possible. I will use some of the data (in aggregate) in the meetup.
* [Join the Slack channel by clicking here](https://join.slack.com/t/epsy630-spring2021/shared_invite/zt-lrleoomo-82Zok02xEmF_dWIilEAkrA). This will be our primary mode of communication. For private communications, you can either send private Slack messages or email me at [jbryer@albany.edu](mailto:jbryer@albany.edu).
* The best way to reach me is by Slack or email at [jbryer@albany.edu](mailto:jbryer@albany.edu). If you would prefer to talk on the phone or setup a Zoom session, it is best to suggest some times by email first.
* Our class meetings will be on Tuesday at 4:30pm. 
* I am looking forward to getting to know everyone and a fantastic semester! Good luck!


<!-- iframe width="560" height="315" src="https://www.youtube.com/embed/yIyferBnO24" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe -->

<!-- iframe src="/slides/2019-01-24-Intro_to_Course.html#1" width="1024px" height="768px"  frameborder="0" allowfullscreen>
</iframe -->
